---

- name: Manage NFS shares
  hosts: [ 'devo_service_nfs' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: devo.nfs
      tags: [ 'role::nfs' ]
